name          'puppet-site'
version       '0.1.0'
source        'https://github.com/nrvale0/puppet-site'
author        'Nathan Valentine - < nrvale0@gmail.com | nathan@puppetlabs.com >'
license       'Apache 2.0'
summary       'A site module with common Roles and Profiles.'
description   ''
project_page  'https://github.com/nrvale0/puppet-site'

dependency 'puppetlabs/stdlib'
